import React, { useState, useCallback } from "react";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

import { AddMediaOptions } from "../components/AddMediaOptions";
import { AddMediaFromSearchModal } from "../components/modals/AddMediaFromSearchModal";
import { ExternalMediaResult } from "../services/externalMediaService";
import { addMedia } from "../services/mediaService";

import type { MediaItem } from "../types";
import { useToast } from "../context/ToastContext";

/**
 * Página simples para adicionar mídia.
 * Mostra as opções (Buscar online / Adicionar manualmente) e,
 * quando o usuário escolhe um resultado externo, abre o modal de confirmação.
 */
export const AddMediaPage: React.FC = () => {
  const navigate = useNavigate();
  const { showSuccess, showError } = useToast();

  const [selectedResult, setSelectedResult] =
    useState<ExternalMediaResult | null>(null);

  const handleAddFromSearch = useCallback(
    async (newItem: MediaItem) => {
      try {
        // Strip properties that will be generated by DB or shouldn't be set manually
        const { id, createdAt, updatedAt, ...rest } = newItem;
        await addMedia(rest);
        showSuccess("Mídia adicionada!");
        navigate(-1);
      } catch (error) {
        console.error(error);
        showError("Erro ao adicionar mídia");
      } finally {
        setSelectedResult(null);
      }
    },
    [showSuccess, showError, navigate],
  );

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      {/* Cabeçalho */}
      <div className="flex items-center gap-3 mb-6">
        <button
          onClick={() => navigate(-1)}
          className="p-2 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10"
          aria-label="Voltar"
          title="Voltar"
        >
          <ArrowLeft size={18} />
        </button>
        <h1 className="text-2xl font-bold text-white">Adicionar Mídia</h1>
      </div>

      {/* Card com as opções */}
      <div className="bg-slate-800/70 border border-white/10 rounded-2xl p-6">
        <AddMediaOptions
          onExternalResultSelect={(r) => setSelectedResult(r)}
          onManualAdd={() => {
            navigate("/media/new");
          }}
        />
      </div>

      {/* Modal de adicionar a partir da busca online */}
      {selectedResult && (
        <AddMediaFromSearchModal
          selectedResult={selectedResult}
          onAdd={handleAddFromSearch}
          onClose={() => setSelectedResult(null)}
        />
      )}
    </div>
  );
};

export default AddMediaPage;
